//! The playground's typesync output, generated by the CLI built from this
//! checkout, once per test run and configuration.

use crate::binary::{copy_playground, evenframe};
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Mutex;

/// A copy of the playground named `name`, with `edit_config` applied to its
/// `evenframe.toml`, after `evenframe typesync` ran in it.
pub fn generated(name: &str, edit_config: fn(String) -> String) -> PathBuf {
    static GENERATED: Mutex<BTreeMap<String, PathBuf>> = Mutex::new(BTreeMap::new());
    let mut generated = GENERATED.lock().unwrap();
    if let Some(dir) = generated.get(name) {
        return dir.clone();
    }

    let dir = Path::new(env!("CARGO_TARGET_TMPDIR"))
        .join("playground_output")
        .join(name);
    if dir.exists() {
        fs::remove_dir_all(&dir).unwrap();
    }
    copy_playground(&dir);
    let config = dir.join("evenframe.toml");
    fs::write(&config, edit_config(fs::read_to_string(&config).unwrap())).unwrap();

    let output = Command::new(evenframe())
        .arg("typesync")
        .current_dir(&dir)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "evenframe typesync failed\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    generated.insert(name.to_string(), dir.clone());
    dir
}
